OPS: upgrade to gradle 7.5.1
OpenLiberty/yoko pull request #185
Opened 2022-10-17 13:51 UTC by joe-chacko

2022-10-18 23:06 UTC, ngmr requested changes

2022-10-19 10:01 UTC, joe-chacko commented on build.gradle
> -    testLib
done

2022-10-19 10:01 UTC, joe-chacko commented on common.bnd
> +Bundle-DocURL: https://geronimo.apache.org/maven/yoko/${project.version}/${project.name}
done

2022-10-19 11:16 UTC, joe-chacko commented on yoko-core/build.gradle
> +  artifactImplementation.extendsFrom implementation, testLib
correct

2022-10-19 11:18 UTC, joe-chacko commented on yoko-core/build.gradle
> +  testImplementation.extendsFrom testLib
correct

2022-10-19 11:19 UTC, joe-chacko commented on yoko-core/build.gradle
> +  testLib "org.hamcrest:hamcrest:2.1"
correct

2022-10-19 11:20 UTC, joe-chacko commented on yoko-core/build.gradle
> +      if ("test" != srcSet.name) return
done

2022-10-19 11:21 UTC, joe-chacko commented on yoko-test/build.gradle
> +  implementation project(":yoko-spec-corba"), project(':yoko-core')
agree

2022-10-19 11:21 UTC, joe-chacko commented on yoko-test/build.gradle
> +  implementation project(":yoko-spec-corba"), project(':yoko-core')
done

2022-10-19 11:22 UTC, joe-chacko commented on yoko-spec-corba/bnd.bnd
> +-buildpath: \
done

2022-10-19 11:28 UTC, joe-chacko commented on build.gradle
> -      instruction 'Import-Package'         , 'sun.*;resolution:=optional,*'
Proved: 
```
bnd **/libs/*.jar | grep 'sun\.'
                                        sun.misc;resolution:=optional
                                        sun.reflect;resolution:=optional
```

This is handled inside rmi-impl's build.gradle, which is where these packages are used.

2022-10-19 16:12 UTC, joe-chacko commented on build.gradle
> -          // declare 'provided' scope dependencies in the pom.xml
The dependencies are correct in the new versions, but some duplication has been lost.
The 'provided' scope is missing, but I don't think this matters.

2022-10-20 14:38 UTC, ngmr approved these changes
As addressing the commented out 'gradle.buildFinished' stanza will be addressed (removed) in a subsequent issue, I'm happy with the change.

2022-10-20 14:38 UTC, merged